// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHeroesAPI.Data;

#nullable disable

namespace MyHeroesAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyHeroesAPI.Models.Heroi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Altura")
                        .HasColumnType("real");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NomeHeroi")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Herois");
                });

            modelBuilder.Entity("MyHeroesAPI.Models.HeroisSuperpoderes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HeroiId")
                        .HasColumnType("int");

                    b.Property<int>("SuperpoderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeroiId");

                    b.HasIndex("SuperpoderId");

                    b.ToTable("HeroisSuperpoderes");
                });

            modelBuilder.Entity("MyHeroesAPI.Models.Superpoderes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Superpoder")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Superpoderes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Superpoder = "Vôo"
                        },
                        new
                        {
                            Id = 2,
                            Superpoder = "Super Força"
                        },
                        new
                        {
                            Id = 3,
                            Superpoder = "Telepatia"
                        },
                        new
                        {
                            Id = 4,
                            Superpoder = "Invisibilidade"
                        },
                        new
                        {
                            Id = 5,
                            Superpoder = "Super velocidade"
                        },
                        new
                        {
                            Id = 6,
                            Superpoder = "Teletransporte"
                        },
                        new
                        {
                            Id = 7,
                            Superpoder = "Regeneração Acelerada"
                        },
                        new
                        {
                            Id = 8,
                            Superpoder = "Manipulação de Elementos"
                        },
                        new
                        {
                            Id = 9,
                            Superpoder = "Campo de Força"
                        },
                        new
                        {
                            Id = 10,
                            Superpoder = "Controle Mental"
                        });
                });

            modelBuilder.Entity("MyHeroesAPI.Models.HeroisSuperpoderes", b =>
                {
                    b.HasOne("MyHeroesAPI.Models.Heroi", "Heroi")
                        .WithMany("HeroisSuperpoderes")
                        .HasForeignKey("HeroiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyHeroesAPI.Models.Superpoderes", "Superpoderes")
                        .WithMany("HeroisSuperpoderes")
                        .HasForeignKey("SuperpoderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heroi");

                    b.Navigation("Superpoderes");
                });

            modelBuilder.Entity("MyHeroesAPI.Models.Heroi", b =>
                {
                    b.Navigation("HeroisSuperpoderes");
                });

            modelBuilder.Entity("MyHeroesAPI.Models.Superpoderes", b =>
                {
                    b.Navigation("HeroisSuperpoderes");
                });
#pragma warning restore 612, 618
        }
    }
}
